
rem Clean up the results directory
rmdir /S /Q results
mkdir results

rem Synthesize the Verilog Wrapper Files
rem creating the xst project file using $XILINX reference
echo verilog work %XILINX%/verilog/src/iSE/unisim_comp.v > xst.prj
echo verilog work ..\example_design\tri_mode_eth_mac_mod.v > xst.prj
echo verilog work ..\example_design\fifo\tx_client_fifo.v >> xst.prj
echo verilog work ..\example_design\fifo\rx_client_fifo.v >> xst.prj
echo verilog work ..\example_design\fifo\ten_100_1g_eth_fifo.v >> xst.prj
echo verilog work ..\example_design\address_swap_module.v >> xst.prj
echo verilog work ..\example_design\johnson_cntr.v >> xst.prj
echo verilog work ..\example_design\physical\rgmii_v2_0_if.v >> xst.prj
echo verilog work ..\example_design\tx_clk_gen.v >> xst.prj
echo verilog work ..\example_design\rx_clk_gen.v >> xst.prj
echo verilog work ..\example_design\clk_gen.v >> xst.prj
echo verilog work ..\example_design\tri_mode_eth_mac_block.v >> xst.prj
echo verilog work ..\example_design\tri_mode_eth_mac_locallink.v >> xst.prj
echo verilog work ..\example_design\tri_mode_eth_mac_example_design.v >> xst.prj
echo 'Synthesizing verilog sample design with XST';
xst -ifn xst.scr
copy tri_mode_eth_mac_example_design.ngc .\results\

rem Copy the EDIF's generated by Coregen
echo 'Copying files from the netlist directory to the results directory'
copy ..\..\tri_mode_eth_mac.ngc results\

rem  Copy the constraints files generated by Coregen
echo 'Copying files from constraints directory to results directory'
copy ..\example_design\tri_mode_eth_mac_example_design.ucf results\

cd results

echo 'Running ngdbuild'
ngdbuild tri_mode_eth_mac_example_design

map tri_mode_eth_mac_example_design -o mapped.ncd

echo 'Running par'
par -n 0 -s 1 -ol high -w mapped.ncd routed.dir mapped.pcf
copy /B routed.dir\*.ncd routed.ncd

echo 'Running trce'
trce -u -e 10 routed -o routed mapped.pcf

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level Verilog model'
netgen -ofmt verilog -pcf mapped.pcf -sim -dir . -tm tri_mode_eth_mac_example_design -w -sdf_anno false routed.ncd routed.v
